### ISSUE TITLE
typing error on the page "Measurements" > "Center back neck to Waist"

### ISSUE THREAD

**Issue by Slylele** [freesewing/markdown#69]
Last sentence starts with "o" instead of "To"
https://en.freesewing.org/docs/measurements/centerbacknecktowaist/

**Comment by Slylele** [comment]
New typing error: https://fr.freesewing.org/docs/measurements/highpointshouldertobust/ : 
"but roll towards your shoulder (as in, it should sit in the middle) Tp measure your HPS to bust, "
should be
"but roll towards your shoulder (as in, it should sit in the middle)**. To** measure your HPS to bust, "

**Comment by joostdecock** [comment]
Pro tip: What DE/FR/ES/NL needs to be translated via Crowdin, you can adapt the original English pages in this repository: https://github.com/freesewing/markdown

See the editor docs for some more info: https://freesewing.dev/guides/editor/

Just navigate to the file with the issue (eg: https://github.com/freesewing/markdown/blob/develop/org/docs/measurements/highpointshouldertobust/en.md ) click the pencil icon, and submit your changes.

I'm just mentioning it because if you know how to do it, fixing it is no more work than reporting it ;)

**Comment by Slylele** [comment]
That's good to know; indeed it's as quick as reporting the issue ;)
